# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: dfcdaf0b25124fa7cd4c9d591382a1fe69a93c67 $
Configuration parameters:
  url = http://10.0.21.132
  name = siriuswiki

Please do not commit this to the Git repository!
"""

from pywikibot import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'siriuswiki'
        self.langs = {
            'en': '10.0.21.132',
        }



    def scriptpath(self, code):
        return {
            'en': '/mediawiki-1.23.1',
        }[code]

    def version(self, code):
        return {
            'en': u'1.23.1',
        }[code]
