#!/bin/sh
# \
exec oagtclsh "$0" "$@"

# Script computeLifetime
# Used to compute the touschek lifetime from the local momentum aperture
# including a cap on the maximum momentum aperture.

set auto_path [linsert $auto_path 0  $env(OAG_TOP_DIR)/oag/apps/lib/$env(HOST_ARCH)]
APSStandardSetup

set usage {usage: computeLifetime -rootname <string> [-msectors <number>1] [-current <mA>(100)] [-bunches <number>(24)] [-coupling <value>(0.01)] [-sigmas <mm>(3.5)] [-deltaLimit <%>(2.35)]}
set rootname ""
set coupling .01
set current 500.0
set bunches 864
set sigmas 3.5
set deltaLimit 6.0
set args $argv
if {[APSStrictParseArguments {rootname current bunches coupling sigmas msectors deltaLimit}] || ![string length $rootname]} {
    return -code error "$usage"
}

if ![file exists ${rootname}.mmap] {
    puts stderr "not found: ${rootname}.mmap"
}
if ![file exists ${rootname}.twi] {
    puts stderr "not found: ${rootname}.twi"
}

# Figure out how many sectors are covered by the LMA data
set circumference 518.396
set sectors 10
set lsector [expr (1.0*$circumference)/$sectors]
set bunchCurrent [expr $current/(1.0*$bunches)]
set charge [expr $bunchCurrent*($circumference/299792458.0)*1e6]

exec sddssplit ${rootname}.mmap -extension=mmap1
set nsteps [eval exec ls [glob *.mmap1] | wc -l]
set nomes []
for {set ii 1} {$ii <= $nsteps} {incr ii} {
    set i [format "%03d" $ii]
    # para evitar loops infinitos do touschekLifetime quando a máquina for instável
    exec sddsprocess ${rootname}$i.mmap1 -pipe=out "-redefine=col,deltaPositive,deltaPositive 0.001 < ? 0.001 : deltaPositive $ ,units=m" \
       | sddsprocess -pipe=in ${rootname}$i.mmap1  "-redefine=col,deltaNegative,deltaNegative -0.001 > ? -0.001 : deltaNegative $ ,units=m"
    #
    exec sddssort ${rootname}$i.mmap1 -pipe=out -column=s,decreasing \
    | sddsprocess -pipe=in ${rootname}$i.mmap2 "-redefine=col,s,$lsector s -"
    exec sddscombine ${rootname}$i.mmap1 ${rootname}$i.mmap2 ${rootname}$i.mmap -merge

    set sMax [exec sddsprocess ${rootname}$i.mmap -pipe=out -process=s,max,sMax | sdds2stream -pipe -page=1 -parameter=sMax]
    set msectors [expr int($sMax/$lsector+0.5)]
    set number [expr int((1.0*$sectors)/$msectors+0.5)]

    eval exec sddscombine [APSReplicateItem -item ${rootname}$i.mmap -number $number] -pipe=out \
    | sddsprocess -pipe "{-redefine=col,s,s i_page 1 - $sMax $sectors / * $msectors * +,units=m}" \
    | sddscombine -pipe -merge \
    | sddsprocess -pipe=in ${rootname}$i.mmapxt -filter=col,s,0,$sMax
    # $rootname.mmapxt now contains the LMA for the full ring, created by replicating the data for $msectors sectors
    # a sufficient number of times
    set mmapFile ${rootname}$i.mmapxt

    exec touschekLifetime ${rootname}$i.ltime -twiss=${rootname}.twi -aperture=$mmapFile \
          -coupling=$coupling -charge=$charge -length=$sigmas \
          -deltaLimit=$deltaLimit -ignoreMismatch

    lappend nomes ${rootname}$i.ltime
}

eval exec sddscombine $nomes $rootname.ltime
